version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.trimble:*"  # Ignore all private dependencies
      - dependency-name: "*:*"  # Ignore all dependencies from private registries
    groups:
      gradle-dependencies:
        patterns:
          - "*"
