version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "Dependabot-Implementation"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "16:30"
    commit-message:
      prefix: "dependabot"
    groups:
      gradle-dependencies:
        patterns:
          - "*"