version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        source-url: "https://artifactory.trimble.tools"
    groups:
      gradle-dependencies:
        patterns:
          - "*"
