version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "Dependabot-Implementation"
    schedule:
      interval: "daily"
    groups:
      gradle-dependencies:
        patterns:
          - "*"