version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "artifactory.trimble.tools:*"  # Ignore all Trimble-specific dependencies
    groups:
      gradle-dependencies:
        patterns:
          - "*"
