version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    registries: []  
    groups:
      gradle-dependencies:
        patterns:
          - "*"
