package com.trimble.ttm.commons.utils

const val TIME_FIELD = "time field"
const val DATE_FIELD = "date field"
const val BARCODE_FIELD = "barcode field"
const val CANCEL_BUTTON = "cancel button"
const val OK_BUTTON = "ok button"
const val SAVE_BUTTON = "save button"
const val CLEAR_BUTTON = "clear button"
const val TIME_FIELD_ICON = "time field icon"
const val DATE_FIELD_ICON = "date field icon"
const val DATE_TIME_FIELD_ICON = "date time field icon"
const val BARCODE_FIELD_ICON = "barcode field icon"
const val DATE_ICON = "date icon"
const val TIME_ICON = "date icon"
const val DATE_TIME_ICON = "date time icon"
const val TITLE_TEXT = "title text"
const val CUSTOM_NUMERIC_FIELD = "Custom Numeric Field"
const val CUSTOM_TEXT_FIELD = "Custom text Field"
const val TAP_TO_SCAN_CLICK = "Tap to scan click"
const val TAP_TO_SCAN = "tap to scan"
const val BARCODE_LIST_ITEM = "barcode list item"
const val BARCODE_SCAN_LIST_ITEM = "barcode scan list item"
const val CLOSE_ICON_LIST_ITEM = "close icon list item"
const val FAB_ICON = "fab icon"
const val DATE_TIME_FIELD = "date time field"

