package com.trimble.ttm.routemanifest

const val ALERT_DIALOG_WAIT_TIME = 10000L
const val ROUTE_CALCULATION_WAIT_TIME = 10000L
const val ETA_CALCULATION_TIME = 10000L
const val PREVIOUS_ARROW_WAIT_TIME = 3000L
const val ACTIVE_TRIP_TAG_TIME = 6000L
const val WAIT_TIME_TWO_SECONDS = 2000L
const val FIRST_POSITION = 0
const val SECOND_POSITION = 1
const val THIRD_POSITION = 2
const val FOURTH_POSITION = 3
const val FIRST_STOP_NAME = "Only Approach Action"
const val ARRIVE_BUTTON_TEXT = "ARRIVE"
const val DEPART_BUTTON_TEXT = "DEPART"
const val ARRIVE_COMPLETE_BUTTON_TEXT = "ARRIVE-COMPLETE"
const val DEPART_COMPLETE_BUTTON_TEXT = "DEPART-COMPLETE"
const val START_BUTTON_TEXT = "START TRIP"
const val ALERT_YES_BUTTON_TEXT = "Yes"
const val ALERT_NO_BUTTON_TEXT = "No"
const val ALERT_OK_BUTTON_TEXT = "OK"
const val ALERT_CANCEL_BUTTON_TEXT = "CANCEL"
const val MILES_TEXT = "Miles"
const val STOPS_TEXT = "Stop(s)"
const val ETA_TEXT = "Estimated Drive Time"
const val ETA_LABEL_TEXT = "Location Based ETA"
const val ARRIVAL_LABEL_TEXT = "Arrival"
const val DEPARTURE_LABEL_TEXT = "Departure"
const val ALERT_TEXT = "Alert"
const val LIST_SECTION_TEXT = "LIST"
const val TIMELINE_SECTION_TEXT = "TIMELINE"
const val YOUR_TRIP_ALERT_TEXT = "Your trip"
const val ACTIVE_TRIP_TAG_TEXT = "Active Trip"
const val MESSAGING_TEXT = "Messaging"
const val SENT_TEXT = "Sent"
const val TRASH_TEXT = "Trash"
const val DRAFT_TEXT = "Draft"
const val INBOX_TEXT = "Inbox"
const val FORMS_TEXT = "Forms"
const val TRIP_LIST_TEXT = "Trip List"
const val STOP_LIST_TEXT = "Stop List"
const val INSPECTIONS_TEXT = "Inspections"
const val DISPATCH_ID = "DispatchId"
